# determine absolute path of *this* Makefile
BASE_DIR = $(PWD)

# Start editing below

# OpenStream toplevel installation directory
INST_DIR = $(BASE_DIR)/install

# GCC build directory
GCC_BUILD_DIR = $(BASE_DIR)/gcc/build

# Directory for external library dependence sources
ARCHIVES_DIR = $(BASE_DIR)/extras/archives

# Directory for external library dependence builds
CONTRIB_DIR = $(BASE_DIR)/extras/contrib

