# determine absolute path of *this* Makefile
THIS_DIR = $(dir $(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))

# Start editing below

# OpenStream toplevel installation directory
INST_DIR = $(THIS_DIR)/../install

# GCC without OpenStream support
PLAIN_GCC = /usr/bin/gcc

# GCC with OpenStream support
GCC = $(INST_DIR)/bin/gcc

# GCC cross compiler for x86 with OpenStream support
CC_X86 = $(GCC)

# Path to the Mercurium compiler executable. Set to an empty value if you're
# not interested in benchmarks built with MCC.
MCC =

# Path to the Intel Math Kernel Library
MKLROOT=

# Path to the Intel Compiler executable
ICC=

# Path to the Intel Compiler archiver
XIAR=

# Path to the ICC libraries (e.g., libimf.a and libirc.a)
ICC_LIB_DIR=

# ICC libraries (e.g., libimf.a and libirc.a)
ICC_STATIC_LIBS=

# Path to the installation of PLASMA
PLASMA_ROOT=

# If set to TRUE, a run-time search path for libwstream_df.so
# is set for the example programs
USE_RPATH=TRUE

# Path to the cilk compiler executable. Set to an empty value if you're
# not interested in cilk benchmarks.
CILKC = $(INST_DIR)/bin/cilkc

LIB_DIR = $(INST_DIR)/lib
LIB64_DIR = $(INST_DIR)/lib64

BLAS_PREFIX = $(THIS_DIR)/../install/
BLAS_INC_DIR = $(BLAS_PREFIX)/include
BLAS_LIB_DIR = $(BLAS_PREFIX)/lib

CBLAS_PREFIX = $(THIS_DIR)/../install/
CBLAS_INC_DIR = $(CBLAS_PREFIX)/include
CBLAS_LIB_DIR = $(CBLAS_PREFIX)/lib

LAPACK_PREFIX = $(THIS_DIR)/../install/
LAPACK_INC_DIR = $(LAPACK_PREFIX)/include
LAPACK_LIB_DIR = $(LAPACK_PREFIX)/lib

FFTW_PREFIX = $(INST_DIR)
FFTW_INC_DIR = $(FFTW_PREFIX)/include
FFTW_LIB_DIR = $(FFTW_PREFIX)/lib

LIBWSTREAM_DF_LIB_DIR = $(LIB64_DIR)
LD_RPATH_FLAGS=

ifeq ($(USE_RPATH),TRUE)
LD_RPATH_FLAGS=-Wl,-rpath,$(LIBWSTREAM_DF_LIB_DIR) \
		-Wl,-rpath,$(LAPACK_LIB_DIR) \
		-Wl,-rpath,$(BLAS_LIB_DIR) \
		-Wl,-rpath,$(CBLAS_LIB_DIR) \
		-Wl,-rpath,$(FFTW_LIB_DIR) \
		-Wl,-rpath,$(LIB_DIR) \
		-Wl,-rpath,$(LIB64_DIR)
endif

DEFAULT_OPENSTREAM_CFLAGS = -fno-openstream-trace-view-access
